# -*- coding: utf-8 -*-
"""caesar.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7WtCElX25ZnRYoMB5yK7CYtKOxIY6Rc
"""

import typing as tp


def encrypt_caesar(plaintext: str, shift: int = 3) -> str:
    """
    Encrypts plaintext using a Caesar cipher.

    >>> encrypt_caesar("PYTHON")
    'SBWKRQ'
    >>> encrypt_caesar("python")
    'sbwkrq'
    >>> encrypt_caesar("Python3.6")
    'Sbwkrq3.6'
    >>> encrypt_caesar("")
    ''
    """
    ciphertext_chars = []  # используем список для накопления символов
    shift_amount = shift % 26
    for ch in plaintext:
        if ch.isalpha():
            if ch.isupper():
                base = ord('A')
            else:
                base = ord('a')
            shifted = chr((ord(ch) - base + shift_amount) % 26 + base)
            ciphertext_chars.append(shifted)  # добавляем в список
        else:
            ciphertext_chars.append(ch)  # добавляем в список
    return ''.join(ciphertext_chars)  # объединяем список в строку


def decrypt_caesar(ciphertext: str, shift: int = 3) -> str:
    """
    Decrypts a ciphertext using a Caesar cipher.

    >>> decrypt_caesar("SBWKRQ")
    'PYTHON'
    >>> decrypt_caesar("sbwkrq")
    'python'
    >>> decrypt_caesar("Sbwkrq3.6")
    'Python3.6'
    >>> decrypt_caesar("")
    ''
    """
    plaintext_chars = []  # используем список для накопления символов
    shift_amount = shift % 26
    for ch in ciphertext:
        if ch.isalpha():
            if ch.isupper():
                base = ord('A')
            else:
                base = ord('a')
            shifted = chr((ord(ch) - base - shift_amount) % 26 + base)
            plaintext_chars.append(shifted)  # добавляем в список
        else:
            plaintext_chars.append(ch)  # добавляем в список
    return ''.join(plaintext_chars)  # объединяем список в строку


def caesar_breaker_brute_force(ciphertext: str, dictionary: tp.Set[str]) -> int:
    """
    Brute force breaking a Caesar cipher.
    """
    best_shift = 0
    max_matches = 0

    for shift in range(26):  # пробуем все возможные сдвиги от 0 до 25
        decrypted = decrypt_caesar(ciphertext, shift)
        # разбиваем расшифрованный текст на слова (по пробелам и знакам препинания)
        words = decrypted.split()
        matches = sum(1 for word in words if word.lower() in dictionary)

        if matches > max_matches:
            max_matches = matches
            best_shift = shift

    return best_shift
