# -*- coding: utf-8 -*-
"""vigenere

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCn14ibsGZlkb5fFkOF2DXfZhKwNOGCC
"""

def encrypt_vigenere(plaintext: str, keyword: str) -> str:
    """
    Encrypts plaintext using a Vigenere cipher.

    >>> encrypt_vigenere("PYTHON", "A")
    'PYTHON'
    >>> encrypt_vigenere("python", "a")
    'python'
    >>> encrypt_vigenere("ATTACKATDAWN", "LEMON")
    'LXFOPVEFRNHR'
    """
    key_len = len(keyword)
    key_index = 0

    for ch in plaintext:
        if ch.isalpha():
            shift = ord(keyword[key_index % key_len].lower()) - ord('a')
            if ch.isupper():
                shifted = chr((ord(ch) - ord('A') + shift) % 26 + ord('A'))
            else:
                shifted = chr((ord(ch) - ord('a') + shift) % 26 + ord('a'))
            ciphertext.append(shifted)
        else:
            ciphertext.append(ch)
        key_index += 1

    return ''.join(ciphertext)


def decrypt_vigenere(ciphertext: str, keyword: str) -> str:
    """
    Decrypts a ciphertext using a Vigenere cipher.

    >>> decrypt_vigenere("PYTHON", "A")
    'PYTHON'
    >>> decrypt_vigenere("python", "a")
    'python'
    >>> decrypt_vigenere("LXFOPVEFRNHR", "LEMON")
    'ATTACKATDAWN'
    """
    plaintext = []
    key_len = len(keyword)
    key_index = 0

    for ch in ciphertext:
        if ch.isalpha():
            shift = ord(keyword[key_index % key_len].lower()) - ord('a')
            if ch.isupper():
                shifted = chr((ord(ch) - ord('A') - shift) % 26 + ord('A'))
            else:
                shifted = chr((ord(ch) - ord('a') - shift) % 26 + ord('a'))
            plaintext.append(shifted)
        else:
            plaintext.append(ch)
        key_index += 1

    return ''.join(plaintext)